# ============================================
# DreamWork - 사냥꾼 (Hunter) 직업 설정
# ============================================
# 야생의 수호자 - 몬스터 사냥, 펫 테이밍, 보스 레이드 주도

id: "hunter"
display_name: "사냥꾼"
description: "야생의 수호자 - 몬스터 사냥, 펫 테이밍, 용병 활동"
icon: "BOW"
max_level: 100
exp_formula: "150 + (level * 30) + (level^2 * 5)"

# ============================================
# 스탯 보너스 (레벨당)
# ============================================
# Plan: 힘 +0.5%, 치명타 확률 +0.2%, 민첩 +0.1%
stats_per_level:
  STR: 0.5    # 힘 - 근접 공격력
  DEX: 0.2    # 민첩 - 치명타 확률
  CON: 0.1    # 체력 - 카이팅용

# ============================================
# 경험치 획득처 (Plan 기준 XP/Money 테이블)
# ============================================
# | 대상                  | 등급        | 기본 경험치 | 기본 수입 (D) | 비고          |
# |-----------------------|-------------|-------------|---------------|---------------|
# | 좀비/스켈레톤/거미    | 일반        | 2.0         | 1.0           | 가장 기본     |
# | 크리퍼/엔더맨/마녀    | 고급        | 5.0         | 3.0           | 특수 재료     |
# | 피글린/블레이즈       | 네더        | 8.0         | 5.0           | 위험 지역     |
# | 알파 몬스터           | 엘리트      | 50.0        | 100.0         | 필드 미니보스 |
# | 워든/위더             | 보스        | 200.0       | 500.0         | 대량 경험치   |
# | 현상수배범            | 퀘스트      | 100.0       | 1000+         | 선착순 보상   |

triggers:
  # 일반 등급 (Common)
  - type: ENTITY_KILL
    target: ZOMBIE
    exp: 2.0
    money: 1.0
  - type: ENTITY_KILL
    target: SKELETON
    exp: 2.0
    money: 1.0
  - type: ENTITY_KILL
    target: SPIDER
    exp: 2.0
    money: 1.0
  - type: ENTITY_KILL
    target: CAVE_SPIDER
    exp: 3.0
    money: 1.5
  - type: ENTITY_KILL
    target: DROWNED
    exp: 3.0
    money: 1.5
  - type: ENTITY_KILL
    target: HUSK
    exp: 3.0
    money: 1.5
  - type: ENTITY_KILL
    target: STRAY
    exp: 3.0
    money: 1.5
  - type: ENTITY_KILL
    target: SILVERFISH
    exp: 2.0
    money: 1.0
  - type: ENTITY_KILL
    target: SLIME
    exp: 2.0
    money: 1.0
  - type: ENTITY_KILL
    target: MAGMA_CUBE
    exp: 3.0
    money: 1.5
  - type: ENTITY_KILL
    target: PHANTOM
    exp: 4.0
    money: 2.0

  # 고급 등급 (Uncommon)
  - type: ENTITY_KILL
    target: CREEPER
    exp: 5.0
    money: 3.0
  - type: ENTITY_KILL
    target: ENDERMAN
    exp: 5.0
    money: 3.0
  - type: ENTITY_KILL
    target: WITCH
    exp: 5.0
    money: 3.0
  - type: ENTITY_KILL
    target: PILLAGER
    exp: 5.0
    money: 3.0
  - type: ENTITY_KILL
    target: VINDICATOR
    exp: 6.0
    money: 4.0
  - type: ENTITY_KILL
    target: EVOKER
    exp: 8.0
    money: 5.0
  - type: ENTITY_KILL
    target: GUARDIAN
    exp: 6.0
    money: 4.0

  # 네더 등급 (Nether)
  - type: ENTITY_KILL
    target: PIGLIN
    exp: 8.0
    money: 5.0
  - type: ENTITY_KILL
    target: PIGLIN_BRUTE
    exp: 12.0
    money: 8.0
  - type: ENTITY_KILL
    target: BLAZE
    exp: 8.0
    money: 5.0
  - type: ENTITY_KILL
    target: WITHER_SKELETON
    exp: 10.0
    money: 6.0
  - type: ENTITY_KILL
    target: GHAST
    exp: 10.0
    money: 6.0
  - type: ENTITY_KILL
    target: HOGLIN
    exp: 8.0
    money: 5.0

  # 엘리트 등급 (Elite) - 알파 몬스터
  - type: ENTITY_KILL
    target: ELDER_GUARDIAN
    exp: 50.0
    money: 100.0
  - type: ENTITY_KILL
    target: RAVAGER
    exp: 40.0
    money: 80.0

  # 보스 등급 (Boss)
  - type: ENTITY_KILL
    target: WARDEN
    exp: 200.0
    money: 500.0
  - type: ENTITY_KILL
    target: WITHER
    exp: 200.0
    money: 500.0
  - type: ENTITY_KILL
    target: ENDER_DRAGON
    exp: 500.0
    money: 1000.0

# ============================================
# 레벨업 보상 (Plan 2.0 기준)
# ============================================
rewards:
  level_10:
    message: "&c[사냥꾼] &f견습 사냥꾼이 되었습니다! 약점 간파가 해금됩니다."
    stats:
      STR: 3
      DEX: 3
    skill_unlock: "vital_strike"
    mission_required: "kill_zombie_100"
  
  level_30:
    message: "&c[사냥꾼] &f숙련 사냥꾼이 되었습니다! 사냥꾼의 지식이 해금됩니다."
    stats:
      STR: 6
      DEX: 6
      CON: 3
    skill_unlock: "slayer_knowledge"
    unlock: "tracking_skill"  # 추적 스킬 사용 권한
    mission_required: "kill_elite_10"

  level_50:
    message: "&c[사냥꾼] &f전문 사냥꾼이 되었습니다! 사냥용 덫 레시피를 획득합니다."
    stats:
      STR: 10
      DEX: 8
      CON: 5
    unlock: "bear_trap"  # 사냥용 덫 제작 권한
    unlock: "monster_lure"  # 몬스터 미끼 제작 권한
    mission_required: "elite_solo_5"

  level_80:
    message: "&c[사냥꾼] &4학살자&f 자격을 획득했습니다!"
    stats:
      STR: 15
      DEX: 10
      CON: 8
    money: 100000
    unlock: "taming_collar"  # 제압용 목줄 권한
    mission_required: "alpha_kill_20"

  level_100:
    message: "&c[사냥꾼] &4§l전설의 헌터&f 칭호를 획득했습니다!"
    stats:
      STR: 20
      DEX: 15
      CON: 10
    money: 500000
    unlock: "legendary_bow"  # 전설 활 '용살자'
    commands:
      - "lp user %player% parent add master_hunter"
    mission_required: "bounty_complete_100"

# ============================================
# 스킬 목록 (Plan 2.0 기준)
# ============================================
skills:
  # [패시브] 약점 간파 (Vital Strike)
  # - 공격 시 치명타 확률 및 데미지 증가
  # - 레벨에 따라 효과 강화
  vital_strike:
    name: "약점 간파"
    type: PASSIVE
    unlock_level: 10
    description: "공격 시 치명타가 발동할 확률이 증가합니다."
    scaling:
      "10-29":
        crit_chance: 0.10        # 10% 확률
        crit_damage: 1.5         # 1.5배 데미지
      "30-49":
        crit_chance: 0.15
        crit_damage: 1.7
      "50-69":
        crit_chance: 0.20
        crit_damage: 1.9
      "70-89":
        crit_chance: 0.25
        crit_damage: 2.0
      "90+":
        crit_chance: 0.30
        crit_damage: 2.5
        speed_boost_on_crit: true  # 치명타 시 1초 이속 증가

  # [패시브] 사냥꾼의 지식 (Slayer's Knowledge)
  # - 몬스터 처치 수에 따라 해당 몹에게 보너스 획득
  # - 도감 시스템과 연동
  slayer_knowledge:
    name: "사냥꾼의 지식"
    type: PASSIVE
    unlock_level: 30
    description: "몬스터를 많이 처치할수록 해당 몹에게 강해집니다."
    # 도감 레벨 설정 (slayer_knowledge 섹션에서 상세 정의)

  # [액티브] 추적 (Tracking)
  # - 특정 몬스터의 위치를 감지
  tracking:
    name: "추적"
    type: ACTIVE
    unlock_level: 30
    cooldown: 60                 # 1분 재사용 대기
    mana_cost: 20
    duration_seconds: 30         # 30초간 발광 효과
    range: 50                    # 50블록 범위
    description: "주변 몬스터에게 발광 효과를 부여하여 추적합니다."

  # [아이템] 사냥용 덫 (Bear Trap)
  # - 설치 시 몬스터 둔화/고정
  bear_trap:
    name: "사냥용 덫"
    type: ITEM_ACTIVE
    unlock_level: 50
    description: "설치 시 밟은 몬스터를 3초간 속박합니다."
    item_id: "bear_trap"
    duration_seconds: 3          # 3초 속박
    damage: 5                    # 5 피해
    cooldown: 30                 # 30초 재사용
    
  # [아이템] 몬스터 미끼 (Monster Lure)
  # - 사용 시 특정 몬스터 유인
  monster_lure:
    name: "몬스터 미끼"
    type: ITEM_ACTIVE
    unlock_level: 50
    description: "사용 시 주변 몬스터들을 유인합니다."
    item_id: "monster_lure"
    range: 30                    # 30블록 범위
    duration_seconds: 10         # 10초간 유인
    
  # [아이템] 제압용 목줄 (Taming Collar)
  # - 체력 낮은 몬스터를 펫으로 테이밍
  taming_collar:
    name: "제압용 목줄"
    type: ITEM_ACTIVE
    unlock_level: 80
    description: "체력 20% 이하 몬스터를 펫으로 포획합니다."
    item_id: "taming_collar"
    health_threshold: 0.20
    success_base_chance: 0.30
    success_per_level: 0.005

# ============================================
# 무기 진화 시스템 (Plan 2.0 신규)
# ============================================
weapon_evolution:
  enabled: true
  
  # 활 진화
  bow_tiers:
    apprentice:
      name: "&7수습생의 활"
      level_required: 10
      base_material: BOW
      bonuses:
        damage_bonus: 0.05
      enchantments:
        - POWER:1
      pdc_data:
        tier: 1
    hunter:
      name: "&e사냥꾼의 활"
      level_required: 30
      base_material: BOW
      bonuses:
        damage_bonus: 0.10
        crit_chance_bonus: 0.05
      enchantments:
        - POWER:2
        - INFINITY:1
      pdc_data:
        tier: 2
    artisan:
      name: "&b장인의 활"
      level_required: 50
      base_material: BOW
      bonuses:
        damage_bonus: 0.15
        crit_chance_bonus: 0.10
        arrow_speed: 1.2
      enchantments:
        - POWER:4
        - INFINITY:1
        - FLAME:1
      pdc_data:
        tier: 3
    legendary:
      name: "&6용살자"
      level_required: 100
      base_material: BOW
      mission_required: "bounty_complete_100"
      bonuses:
        damage_bonus: 0.30
        crit_chance_bonus: 0.20
        armor_penetration: 0.25
        boss_damage: 0.50
      enchantments:
        - POWER:5
        - INFINITY:1
        - FLAME:1
        - PUNCH:2
      pdc_data:
        tier: 4

# ============================================
# 슬레이어 도감 시스템 (Plan: Slayer's Knowledge)
# ============================================
slayer_knowledge:
  enabled: true
  
  # 지식 레벨업 조건
  tiers:
    level_1:
      kills_required: 100
      damage_bonus: 0.05         # 해당 몹에게 +5% 데미지
    level_2:
      kills_required: 500
      damage_bonus: 0.10
      damage_reduction: 0.10     # 해당 몹에게 받는 데미지 -10%
    level_3:
      kills_required: 1000
      damage_bonus: 0.15
      damage_reduction: 0.15
      exp_bonus: 1.5             # 경험치 1.5배
    level_max:
      kills_required: 5000
      damage_bonus: 0.25
      damage_reduction: 0.25
      exp_bonus: 2.0
      money_bonus: 1.5

# ============================================
# 몹 티어 시스템 (Plan: Alpha Monster)
# ============================================
mob_tier:
  enabled: true
  
  # 알파 몬스터 스폰 설정
  alpha:
    spawn_chance: 0.01          # 1% 확률로 알파 스폰
    name_prefix: "&c§l[ALPHA] "
    size_multiplier: 2.0        # 크기 2배
    health_multiplier: 5.0      # 체력 5배
    damage_multiplier: 2.0      # 데미지 2배
    drop_multiplier: 3.0        # 드롭 3배
    exp_multiplier: 10.0        # 경험치 10배
    particle_effect: "FLAME"
    announcement: true          # 스폰 시 서버 알림
    guaranteed_drops:
      - item: "reinforced_leather"
        chance: 1.00
      - item: "monster_essence"
        chance: 0.50

# ============================================
# 현상금 시스템 (Plan: Bounty)
# ============================================
bounty_system:
  enabled: true
  
  # 자동 발생 현상금
  auto_bounty:
    interval: 600              # 10분마다
    reward_base: 1000          # 기본 보상 1000D
    reward_per_distance: 0.5   # 거리당 추가 보상
    exp_base: 100.0
    announcement: "&c[현상수배] &f좌표 X: %x%, Z: %z% 근처의 &e%mob%&f을 처치하시오!"

# ============================================
# 블러드 문 이벤트 (Plan: Blood Moon)
# ============================================
blood_moon:
  enabled: true
  cycle_days: 7                 # 게임 7일마다
  spawn_multiplier: 3.0         # 몬스터 스폰 3배
  mob_speed_boost: 0.20         # 이동속도 +20%
  mob_damage_boost: 0.30        # 공격력 +30%
  exp_multiplier: 2.0           # 경험치 2배
  announcement: "&4§l[블러드 문] &c붉은 달이 떠올랐습니다... 몬스터들이 광폭화합니다!"

# ============================================
# 특수 아이템 드롭
# ============================================
special_drops:
  # 강화 가죽 (갑옷 안감 재료)
  reinforced_leather:
    enabled: true
    base_chance: 0.05
    trigger_mobs:
      - ZOMBIE
      - SKELETON
      - SPIDER
      - CAVE_SPIDER

  # 키틴질 갑각
  chitin_shell:
    enabled: true
    base_chance: 0.08
    trigger_mobs:
      - SPIDER
      - CAVE_SPIDER
      - SILVERFISH
      - ENDERMITE

  # 몬스터 에센스
  monster_essence:
    enabled: true
    base_chance: 0.02
    level_bonus: 0.0002
    trigger_mobs: "ALL"

  # 영혼의 조각 (보스 토템 재료)
  soul_fragment:
    enabled: true
    base_chance: 0.01
    trigger_mobs:
      - WITHER_SKELETON
      - GHAST
      - BLAZE
      - ENDERMAN
