# ============================================
# DreamWork - 농부 (Farmer) 직업 설정
# ============================================
# 풍요의 공급자 - 식량 공급, 버프 요리 생산, 특수 작물 재배

id: "farmer"
display_name: "농부"
description: "풍요의 공급자 - 식량 공급, 버프 요리 생산, 목축"
icon: "GOLDEN_HOE"
max_level: 100
exp_formula: "100 + (level * 20) + (level^2 * 4)"

# ============================================
# 스탯 보너스 (레벨당)
# ============================================
# Plan: 체력 +0.5 하트, 재생력 +0.2%, 행운 +1
stats_per_level:
  CON: 0.5    # 체력 - 최대 체력 증가
  INT: 0.2    # 지능 - 재생력
  LUCK: 1.0   # 행운 - 추가 드롭, 고등급 작물 확률

# ============================================
# 경험치 획득처 (Plan 기준 XP/Money 테이블)
# ============================================
# | 대상               | 기본 경험치 | 기본 수입 (D) | 비고                 |
# |--------------------|-------------|---------------|----------------------|
# | 밀/감자/당근 수확   | 2.0         | 0.5           | 가장 기초적인 활동   |
# | 호박/수박/사탕수수  | 3.5         | 1.0           | 자동화 농장 효율 고려|
# | 네더 와트/코러스    | 8.0         | 3.0           | 특수 작물 보너스     |
# | 동물 번식 (소/양)   | 15.0        | 10.0          | 사료 소모에 대한 보상|
# | 동물 번식 (말/거북) | 30.0        | 25.0          | 긴 쿨타임 고려       |
# | 황금 작물           | 100.0       | 150.0         | 수확 시 대박 경험치  |

triggers:
  # 기본 작물 (밀/감자/당근)
  - type: BLOCK_BREAK
    target: WHEAT
    exp: 2.0
    money: 0.5
  - type: BLOCK_BREAK
    target: CARROTS
    exp: 2.0
    money: 0.5
  - type: BLOCK_BREAK
    target: POTATOES
    exp: 2.0
    money: 0.5
  - type: BLOCK_BREAK
    target: BEETROOTS
    exp: 2.0
    money: 0.5

  # 대형 작물 (호박/수박)
  - type: BLOCK_BREAK
    target: MELON
    exp: 3.5
    money: 1.0
  - type: BLOCK_BREAK
    target: PUMPKIN
    exp: 3.5
    money: 1.0
  - type: BLOCK_BREAK
    target: SUGAR_CANE
    exp: 3.5
    money: 1.0
  - type: BLOCK_BREAK
    target: CACTUS
    exp: 3.5
    money: 1.0
  - type: BLOCK_BREAK
    target: BAMBOO
    exp: 3.5
    money: 1.0

  # 특수 작물
  - type: BLOCK_BREAK
    target: COCOA
    exp: 8.0
    money: 3.0
  - type: BLOCK_BREAK
    target: NETHER_WART
    exp: 8.0
    money: 3.0
  - type: BLOCK_BREAK
    target: CHORUS_FLOWER
    exp: 8.0
    money: 3.0
  - type: BLOCK_BREAK
    target: SWEET_BERRY_BUSH
    exp: 4.0
    money: 1.5

  # 동물 번식
  - type: BREED
    target: COW
    exp: 15.0
    money: 10.0
  - type: BREED
    target: SHEEP
    exp: 15.0
    money: 10.0
  - type: BREED
    target: PIG
    exp: 15.0
    money: 10.0
  - type: BREED
    target: CHICKEN
    exp: 10.0
    money: 5.0
  - type: BREED
    target: RABBIT
    exp: 12.0
    money: 8.0
  - type: BREED
    target: HORSE
    exp: 30.0
    money: 25.0
  - type: BREED
    target: DONKEY
    exp: 25.0
    money: 20.0
  - type: BREED
    target: TURTLE
    exp: 30.0
    money: 25.0
  - type: BREED
    target: BEE
    exp: 20.0
    money: 15.0

# ============================================
# 레벨업 보상 (Plan 2.0 기준)
# ============================================
rewards:
  level_10:
    message: "&a[농부] &f견습 농부가 되었습니다! 녹색 손길이 해금됩니다."
    stats:
      CON: 5
      INT: 2
      LUCK: 3
    skill_unlock: "green_thumb"
    mission_required: "harvest_wheat_500"
  
  level_30:
    message: "&a[농부] &f숙련 농부가 되었습니다! 대지의 기운이 해금됩니다."
    stats:
      CON: 10
      INT: 5
      LUCK: 5
    skill_unlock: "growth_aura"
    unlock: "cooking_station"  # 요리대 사용 권한
    mission_required: "deliver_crop_1000"

  level_50:
    message: "&a[농부] &f전문 농부가 되었습니다! 풍요의 뿔피리 레시피를 획득합니다."
    stats:
      CON: 15
      INT: 8
      LUCK: 8
    unlock: "horn_of_plenty"  # 뿔피리 제작 레시피
    mission_required: "golden_harvest_10"

  level_80:
    message: "&a[농부] &6대지주&f 자격을 획득했습니다!"
    stats:
      CON: 20
      INT: 10
      LUCK: 10
    money: 100000
    unlock: "restaurant_owner"  # 레스토랑 운영 권한
    mission_required: "buff_food_100"

  level_100:
    message: "&a[농부] &c마스터 농부&f 칭호를 획득했습니다!"
    stats:
      CON: 30
      INT: 15
      LUCK: 15
    money: 500000
    unlock: "legendary_hoe"  # 전설 호미 '대지의 축복'
    commands:
      - "lp user %player% parent add master_farmer"
    mission_required: "cook_legendary_dish"

# ============================================
# 스킬 목록 (Plan 2.0 기준)
# ============================================
skills:
  # [패시브] 녹색 손길 (Green Thumb)
  # - 완전히 자란 작물 수확 시 자동 재파종
  # - 인벤토리에서 씨앗 차감
  green_thumb:
    name: "녹색 손길"
    type: PASSIVE
    unlock_level: 10
    description: "완전히 자란 작물을 수확할 때 자동으로 재파종합니다."
    # 레벨별 스케일링
    scaling:
      "10-29":
        replant_chance: 0.50      # 50% 재파종 확률
        seed_consume: true         # 씨앗 소모
      "30-49":
        replant_chance: 0.75      # 75% 재파종
        seed_consume: true
      "50-69":
        replant_chance: 1.00      # 100% 재파종
        seed_consume: true
      "70+":
        replant_chance: 1.00
        seed_consume: false        # 씨앗 무소모 (행운에서 얻음)
        quality_boost: 0.10        # 2성 확률 +10%

  # [패시브] 대지의 기운 (Growth Aura)
  # - 농부 주변 반경 N블록 내 작물이 천천히 성장
  # - 레벨에 따라 반경 및 성장 속도 증가
  growth_aura:
    name: "대지의 기운"
    type: PASSIVE
    unlock_level: 30
    description: "농부 근처의 작물이 더 빠르게 성장합니다."
    # 매 10~20초마다 주변 작물 한 단계 성장 확률
    check_interval_ticks: 200     # 10초마다 체크
    scaling:
      "30-49":
        radius: 3
        growth_chance: 0.10       # 10% 성장 확률
      "50-69":
        radius: 5
        growth_chance: 0.15
      "70-89":
        radius: 7
        growth_chance: 0.20
      "90+":
        radius: 10
        growth_chance: 0.25
        quality_boost: 0.05       # 3성 확률 +5%

  # [아이템] 풍요의 뿔피리 (Horn of Plenty)
  # - 아이템 사용형 스킬 (농부 전용 호미로 사용)
  # - 범위 내 작물 즉시 성장
  horn_of_plenty:
    name: "풍요의 뿔피리"
    type: ITEM_ACTIVE
    unlock_level: 50
    description: "아이템 사용 시 주변 작물을 즉시 성장시킵니다."
    # 아이템 설정은 items.yml에서 정의
    item_id: "horn_of_plenty"
    cooldown: 180                  # 3분 재사용 대기
    radius: 7
    instant_grow: true
    quality_boost_on_use: true     # 사용 시 품질 상승 확률 증가

# ============================================
# 호미 진화 시스템 (Plan 2.0 신규)
# ============================================
hoe_evolution:
  enabled: true
  tiers:
    apprentice:
      name: "&7수습생의 호미"
      level_required: 10
      base_material: STONE_HOE
      bonuses:
        replant_speed: 1.2
      pdc_data:
        tier: 1
    farmer:
      name: "&e농부의 호미"
      level_required: 30
      base_material: IRON_HOE
      bonuses:
        area_harvest: 3           # 3x3 영역 수확
        replant_speed: 1.4
      pdc_data:
        tier: 2
    artisan:
      name: "&b장인의 호미"
      level_required: 50
      base_material: DIAMOND_HOE
      bonuses:
        area_harvest: 5           # 5x5 영역 수확
        auto_replant: true
        quality_boost: 0.10
      pdc_data:
        tier: 3
    legendary:
      name: "&6대지의 축복"
      level_required: 100
      base_material: NETHERITE_HOE
      mission_required: "cook_legendary_dish"
      bonuses:
        area_harvest: 7           # 7x7 영역 수확
        infinite_durability: true
        all_bonuses: true
      pdc_data:
        tier: 4

# ============================================
# 버프 요리 시스템 (Plan 2.0 신규)
# ============================================
buff_cooking:
  enabled: true
  location_required: "kitchen"     # 주방에서만 제작 가능
  recipes:
    hearty_stew:
      name: "&a든든한 스튜"
      description: "포만감 회복 + 힘 I (3분)"
      ingredients:
        THREE_STAR_CARROT: 3
        THREE_STAR_POTATO: 3
        COOKED_BEEF: 1
      effects:
        - "INCREASE_DAMAGE:1:180"
        - "SATURATION:2:60"
      level_required: 30
    
    golden_feast:
      name: "&6황금빛 만찬"
      description: "모든 스탯 +5%, 재생 II (5분)"
      ingredients:
        THREE_STAR_WHEAT: 5
        GOLDEN_CARROT: 2
        HONEY_BOTTLE: 1
        CUSTOM_GOLDEN_SEED: 1
      effects:
        - "REGENERATION:2:300"
        - "ABSORPTION:2:300"
        - "ALL_STATS_BOOST:0.05:300"
      level_required: 50

# ============================================
# 작물 등급 시스템 (Plan: Crop Quality)
# ============================================
crop_quality:
  enabled: true
  # 등급별 효과
  grades:
    1:  # ★ 일반
      name: "일반"
      prefix: "&f"
      hunger_multiplier: 1.0
      price_multiplier: 1.0
    2:  # ★★ 싱싱한
      name: "싱싱한"
      prefix: "&a싱싱한 "
      hunger_multiplier: 1.5
      price_multiplier: 2.0
    3:  # ★★★ 황금빛
      name: "황금빛"
      prefix: "&6황금빛 "
      hunger_multiplier: 2.0
      price_multiplier: 3.0
      buff_multiplier: 2.0    # 요리 재료 사용 시 버프 효과 2배
  
  # 등급 확률 계산 공식
  # 3성 확률: (level * 0.1)% + (luck * 0.2)%
  # 2성 확률: 10% + (level * 0.3)% + (luck * 0.5)%
  probability:
    three_star:
      base: 0
      per_level: 0.001       # 0.1% per level
      per_luck: 0.002        # 0.2% per luck
    two_star:
      base: 0.10             # 기본 10%
      per_level: 0.003       # 0.3% per level
      per_luck: 0.005        # 0.5% per luck

# ============================================
# 특수 드롭 설정
# ============================================
special_drops:
  # 황금 씨앗 (Plan: 0.1% 확률)
  golden_seed:
    enabled: true
    base_chance: 0.001
    level_bonus: 0.00002
    trigger_actions:
      - HARVEST_CROP
      - BREAK_GRASS
    description: "심으면 황금 작물이 자라며 마법 부여된 사과/다이아 등 드롭"

  # 마법의 비료
  magic_fertilizer:
    recipe:
      - "BONE_MEAL:9"
      - "ROTTEN_FLESH:9"
      - "EMERALD:1"
    effect: "작물 즉시 최대 성장 + 3성 등급 확정"
