id: "farmer"
display_name: "농부"
max_level: 100
exp_formula: "100 + (level * 20) + (level^2 * 4)"

triggers:
  - type: BLOCK_BREAK
    target: WHEAT
    amount: 5.0
  - type: BLOCK_BREAK
    target: CARROTS
    amount: 5.0
  - type: BLOCK_BREAK
    target: POTATOES
    amount: 5.0
  - type: BLOCK_BREAK
    target: BEETROOTS
    amount: 6.0
  - type: BLOCK_BREAK
    target: MELON
    amount: 3.0
  - type: BLOCK_BREAK
    target: PUMPKIN
    amount: 3.0
  - type: BLOCK_BREAK
    target: SUGAR_CANE
    amount: 2.0
  - type: BLOCK_BREAK
    target: CACTUS
    amount: 2.0
  - type: BLOCK_BREAK
    target: COCOA
    amount: 8.0
  - type: BLOCK_BREAK
    target: NETHER_WART
    amount: 10.0

rewards:
  level_10:
    message: "&a[농부] &f자연의 손길(Passive)을 얻었습니다! (작물 수확 시 내구도 감소 확률 50%)"
    stats:
      CON: 5
      INT: 2
    skill_unlock: "nature_touch"
  
  level_30:
    message: "&a[농부] &f풍년(Active)을 기원합니다! (30초간 작물 수확량 2배)"
    stats:
      CON: 10
      INT: 5
    skill_unlock: "bountiful_harvest"

  level_50:
    message: "&a[농부] &f비료 뿌리기(Active)를 배웠습니다! (주변 작물 성장 촉진)"
    stats:
      CON: 15
      INT: 8
    skill_unlock: "fertilizer"

  level_80:
    message: "&a[농부] &6대지주&f 칭호를 획득했습니다!"
    stats:
      CON: 20
      INT: 10
    money: 100000
    skill_unlock: "golden_apple_chance"

stats_per_level:
  CON: 1.0
  INT: 0.5
  LUCK: 0.2

skills:
  nature_touch:
    name: "자연의 손길"
    type: PASSIVE
    unlock_level: 10
    description: "괭이/도구 사용 시 50% 확률로 내구도가 감소하지 않습니다."

  bountiful_harvest:
    name: "풍년"
    type: ACTIVE
    unlock_level: 30
    cooldown: 600
    mana_cost: 50
    description: "30초 동안 농작물 수확 시 2배의 수확물을 얻습니다."

  fertilizer:
    name: "비료 뿌리기"
    type: ACTIVE
    unlock_level: 50
    cooldown: 60
    mana_cost: 30
    description: "바라보는 블록 주변 5x5 범위의 작물을 즉시 성장시킵니다."

  golden_apple_chance:
    name: "황금 사과"
    type: PASSIVE
    unlock_level: 80
    description: "작물 수확 시 0.1% 확률로 황금 사과가 드롭됩니다."
