# ============================================
# DreamWork - 어부 (Fisher) 직업 설정
# ============================================
# 심해의 탐구자 - 해양 자원 공급, 회/버프 음식 생산, 수족관 납품

id: "fisher"
display_name: "어부"
description: "심해의 탐구자 - 해양 자원 공급, 버프 회 생산, 항해"
icon: "FISHING_ROD"
max_level: 100
exp_formula: "100 + (level * 15) + (level^2 * 3)"

# ============================================
# 스탯 보너스 (레벨당)
# ============================================
# Plan: 지능 +1, 낚시 행운 +0.5, 수영 속도 +0.2%
stats_per_level:
  INT: 1.0    # 지능 - 마나/쿨타임 감소
  LUCK: 0.5   # 행운 - 보물/희귀 물고기 확률
  DEX: 0.2    # 민첩 - 수영 속도

# ============================================
# 경험치 획득처 (Plan 기준 XP/Money 테이블)
# ============================================
# | 대상                | 서식지        | 기본 경험치 | 기본 수입 (D) | 비고          |
# |---------------------|---------------|-------------|---------------|---------------|
# | 대구 (Cod)          | 일반 강/바다  | 1.0         | 0.5           | 가장 흔함     |
# | 연어 (Salmon)       | 강/차가운 바다| 3.0         | 2.0           |               |
# | 열대어/복어         | 따뜻한 바다   | 8.0         | 5.0           |               |
# | 참치 (Tuna) [New]   | 난류          | 25.0        | 20.0          | 신규 어종     |
# | 아귀 (Anglerfish)   | 심해/동굴     | 40.0        | 35.0          | 위험 수당     |
# | 보물 상자/인양품    | 모든 바다     | 100.0       | 100.0         | 건축 자재     |
# | 전설의 물고기       | 특정 조건     | 500.0       | 1000.0        | 박제 가능     |

triggers:
  # 일반 물고기
  - type: FISH_CATCH
    target: COD
    exp: 1.0
    money: 0.5
  - type: FISH_CATCH
    target: SALMON
    exp: 3.0
    money: 2.0

  # 특수 물고기
  - type: FISH_CATCH
    target: PUFFERFISH
    exp: 8.0
    money: 5.0
  - type: FISH_CATCH
    target: TROPICAL_FISH
    exp: 8.0
    money: 5.0

  # 보물
  - type: FISH_CATCH
    target: TREASURE
    exp: 100.0
    money: 100.0

  # 신규 커스텀 어종 (월척 시스템에서 처리)
custom_fish:
  tuna:
    exp: 25.0
    money: 20.0
  anglerfish:
    exp: 40.0
    money: 35.0
  legendary_fish:
    exp: 500.0
    money: 1000.0

# ============================================
# 레벨업 보상 (Plan 2.0 기준)
# ============================================
rewards:
  level_10:
    message: "&b[어부] &f견습 어부가 되었습니다! 예민한 감각이 해금됩니다."
    stats:
      INT: 3
      DEX: 3
      LUCK: 5
    skill_unlock: "sensitivity"
    mission_required: "catch_fish_100"
  
  level_30:
    message: "&b[어부] &f숙련 어부가 되었습니다! 어종 지식이 해금됩니다."
    stats:
      INT: 6
      DEX: 5
      LUCK: 8
    skill_unlock: "fish_knowledge"
    unlock: "fish_tank"  # 생선 수조 사용 권한
    mission_required: "catch_rare_fish_20"

  level_50:
    message: "&b[어부] &f전문 어부가 되었습니다! 떡밥 제작 레시피를 획득합니다."
    stats:
      INT: 10
      DEX: 8
      LUCK: 12
    unlock: "chum_recipe"  # 떡밥 제작 레시피
    unlock_item: "ruler"   # 자 아이템 (물고기 크기 측정)
    mission_required: "crown_fish_5"

  level_80:
    message: "&b[어부] &3강태공&f 자격을 획득했습니다!"
    stats:
      INT: 15
      DEX: 10
      LUCK: 15
    money: 100000
    unlock: "aquarium_delivery"  # 수족관 납품 권한
    mission_required: "live_fish_delivery_10"

  level_100:
    message: "&b[어부] &1심해의 지배자&f 칭호를 획득했습니다!"
    stats:
      INT: 20
      DEX: 15
      LUCK: 20
    money: 500000
    unlock: "legendary_rod"  # 전설 낚싯대 '해신의 갈고리'
    commands:
      - "lp user %player% parent add master_fisher"
    mission_required: "catch_legendary_fish"

# ============================================
# 스킬 목록 (Plan 2.0 기준)
# ============================================
skills:
  # [패시브] 예민한 감각 (Sensitivity)
  # - 물고기가 미끼를 무는 대기 시간 감소
  # - 레벨에 따라 감소량 증가
  sensitivity:
    name: "예민한 감각"
    type: PASSIVE
    unlock_level: 10
    description: "물고기가 미끼를 더 빨리 물도록 합니다."
    scaling:
      "10-29":
        wait_reduction_percent: 0.15    # 15% 대기 시간 감소
      "30-49":
        wait_reduction_percent: 0.25    # 25% 감소
      "50-69":
        wait_reduction_percent: 0.35    # 35% 감소
      "70-89":
        wait_reduction_percent: 0.45    # 45% 감소
      "90+":
        wait_reduction_percent: 0.50    # 50% 감소 (최대)
        bite_alert: true                 # 입질 시 사운드 알림

  # [패시브] 어종 지식 (Fish Knowledge)
  # - 낚시 시작 시 해당 바이옴에서 잡을 수 있는 물고기 정보 표시
  # - 레벨에 따라 정보량 증가
  fish_knowledge:
    name: "어종 지식"
    type: PASSIVE
    unlock_level: 30
    description: "낚시 시 현재 바이옴의 물고기 정보를 표시합니다."
    scaling:
      "30-49":
        info_level: 1                    # 어종 이름만 표시
      "50-69":
        info_level: 2                    # 어종 + 기본 시세
      "70-89":
        info_level: 3                    # 어종 + 시세 + 월척 기준
      "90+":
        info_level: 4                    # 전체 정보 + 예상 확률
        xp_bonus: 0.10                   # 경험치 +10%

  # [아이템] 떡밥 (Chum)
  # - 물에 던지면 해당 위치에서 좋은 물고기 확률 증가
  # - 일정 시간 유지 (5분)
  chum:
    name: "떡밥"
    type: ITEM_ACTIVE
    unlock_level: 50
    description: "물에 던지면 5분간 희귀 물고기 확률이 증가합니다."
    item_id: "fishing_chum"
    duration_seconds: 300               # 5분 지속
    radius: 10                          # 효과 반경 10블록
    effects:
      rare_fish_multiplier: 2.0         # 희귀 물고기 2배
      junk_reduction: 0.50              # 쓰레기 50% 감소
      treasure_bonus: 0.25              # 보물 확률 +25%

# ============================================
# 낚싯대 진화 시스템 (Plan 2.0 신규)
# ============================================
rod_evolution:
  enabled: true
  tiers:
    apprentice:
      name: "&7수습생의 낚싯대"
      level_required: 10
      base_material: FISHING_ROD
      bonuses:
        wait_time_reduction: 0.10
      enchantments:
        - LURE:1
      pdc_data:
        tier: 1
    fisherman:
      name: "&e어부의 낚싯대"
      level_required: 30
      base_material: FISHING_ROD
      bonuses:
        wait_time_reduction: 0.20
        luck_bonus: 1
      enchantments:
        - LURE:2
        - LUCK_OF_THE_SEA:1
      pdc_data:
        tier: 2
    artisan:
      name: "&b장인의 낚싯대"
      level_required: 50
      base_material: FISHING_ROD
      bonuses:
        wait_time_reduction: 0.30
        luck_bonus: 2
        durability_save: 0.15
      enchantments:
        - LURE:3
        - LUCK_OF_THE_SEA:2
        - UNBREAKING:3
      pdc_data:
        tier: 3
    legendary:
      name: "&6해신의 갈고리"
      level_required: 100
      base_material: FISHING_ROD
      mission_required: "catch_legendary_fish"
      bonuses:
        wait_time_reduction: 0.50
        luck_bonus: 3
        infinite_durability: true
        legendary_fish_chance: 0.01
      enchantments:
        - LURE:4
        - LUCK_OF_THE_SEA:3
        - MENDING:1
      pdc_data:
        tier: 4

# ============================================
# 회(Sashimi) 가공 시스템 (Plan 2.0 신규)
# ============================================
sashimi_system:
  enabled: true
  location_required: "fishmonger"      # 생선가게에서만 가공 가능
  recipes:
    cod_sashimi:
      input: COD
      output_name: "&a대구 회"
      output_count: 2
      minimum_size_cm: 30               # 30cm 이상만 회 가공 가능
      effects:
        - "WATER_BREATHING:1:180"       # 수중 호흡 3분
      level_required: 30
    
    salmon_sashimi:
      input: SALMON
      output_name: "&a연어 회"
      output_count: 3
      minimum_size_cm: 40
      effects:
        - "DOLPHINS_GRACE:1:180"        # 돌고래의 가호 3분
        - "NIGHT_VISION:1:180"          # 야간 투시 3분
      level_required: 30
    
    pufferfish_sashimi:
      input: PUFFERFISH
      output_name: "&c복어 회 (위험!)"
      output_count: 1
      minimum_size_cm: 20
      effects:
        - "INCREASE_DAMAGE:2:120"       # 힘 II 2분
        - "POISON:1:30"                 # 독 I 30초 (위험!)
      level_required: 50

# ============================================
# 살아있는 물고기 (Live Fish) 시스템 (Plan 2.0 신규)
# ============================================
live_fish_system:
  enabled: true
  fish_keep_duration_minutes: 30        # 생선통에서 30분간 생존
  delivery_bonus_multiplier: 2.0        # 수족관 납품 시 2배 보상
  transportation:
    fish_bucket:
      description: "물고기를 살린 채로 운반합니다"
      capacity: 1
    fish_keep:
      name: "&b생선통"
      description: "물고기를 여러 마리 살려서 운반합니다"
      unlock_level: 50
      capacity: 5
      crafting:
        - "BUCKET:1"
        - "OAK_PLANKS:4"
        - "PRISMARINE_SHARD:2"

# ============================================
# 바이옴별 어종 시스템 (Plan: Biome Fishing)
# ============================================
biome_fishing:
  enabled: true
  
  # 따뜻한 바다 (난류)
  warm_ocean:
    biomes:
      - WARM_OCEAN
      - LUKEWARM_OCEAN
      - DEEP_LUKEWARM_OCEAN
    fish:
      - type: TROPICAL_FISH
        weight: 40
      - type: PUFFERFISH
        weight: 30
      - type: custom:tuna
        weight: 20
      - type: COD
        weight: 10
  
  # 차가운 바다 (한류)
  cold_ocean:
    biomes:
      - COLD_OCEAN
      - DEEP_COLD_OCEAN
      - FROZEN_OCEAN
      - DEEP_FROZEN_OCEAN
    fish:
      - type: SALMON
        weight: 50
      - type: COD
        weight: 40
      - type: custom:icefish
        weight: 10
  
  # 일반 바다
  normal_ocean:
    biomes:
      - OCEAN
      - DEEP_OCEAN
    fish:
      - type: COD
        weight: 50
      - type: SALMON
        weight: 30
      - type: TROPICAL_FISH
        weight: 15
      - type: PUFFERFISH
        weight: 5

  # 심해/동굴
  deep_sea:
    biomes:
      - DEEP_OCEAN
      - DEEP_COLD_OCEAN
      - DEEP_LUKEWARM_OCEAN
      - DRIPSTONE_CAVES
      - LUSH_CAVES
    fish:
      - type: GLOW_SQUID
        weight: 20
      - type: custom:anglerfish
        weight: 15
      - type: COD
        weight: 40
      - type: SALMON
        weight: 25
    # y레벨 조건 (동굴)
    y_level_max: 30

  # 강
  river:
    biomes:
      - RIVER
      - FROZEN_RIVER
    fish:
      - type: SALMON
        weight: 60
      - type: COD
        weight: 40

# ============================================
# 물고기 계측 시스템 (Plan: Size System)
# ============================================
fish_measurement:
  enabled: true
  
  # 물고기별 크기 범위 (cm)
  size_ranges:
    COD:
      min: 20.0
      max: 80.0
      average: 40.0
    SALMON:
      min: 30.0
      max: 100.0
      average: 55.0
    PUFFERFISH:
      min: 10.0
      max: 40.0
      average: 20.0
    TROPICAL_FISH:
      min: 5.0
      max: 25.0
      average: 12.0
    custom_tuna:
      min: 50.0
      max: 200.0
      average: 100.0
    custom_anglerfish:
      min: 30.0
      max: 120.0
      average: 60.0

  # 월척(Crown) 설정 - 상위 5%
  crown:
    threshold: 0.95           # 상위 5%
    price_multiplier: 3.0     # 3배 판매가
    name_color: "&6"          # 황금색 이름
    can_mount: true           # 박제 설치 가능

# ============================================
# 특수 아이템 드롭
# ============================================
special_drops:
  # 심해의 상자 (Plan: Deep Sea Box)
  deep_sea_box:
    enabled: true
    base_chance: 0.005       # 0.5%
    level_bonus: 0.00005
    contents:
      - item: PRISMARINE_SHARD
        weight: 30
        amount: "3-8"
      - item: SEA_LANTERN
        weight: 15
        amount: "1-3"
      - item: HEART_OF_THE_SEA
        weight: 5
        amount: 1
      - item: TRIDENT
        weight: 2
        amount: 1
      - item: ENCHANTED_BOOK
        weight: 10
        amount: 1

  # 유리병 편지
  message_in_bottle:
    enabled: true
    base_chance: 0.01        # 1%
    contents:
      - type: "treasure_map"
        weight: 40
      - type: "quiz"
        weight: 30
      - type: "lore"
        weight: 30
