id: "miner"
display_name: "광부"
max_level: 100
exp_formula: "100 + (level * 25) + (level^2 * 5)"

# 경험치 획득처
triggers:
  # 일반 광물
  - type: BLOCK_BREAK
    target: STONE
    amount: 1.0
  - type: BLOCK_BREAK
    target: COBBLESTONE
    amount: 0.5
  - type: BLOCK_BREAK
    target: DEEPSLATE
    amount: 1.5
  - type: BLOCK_BREAK
    target: DIORITE
    amount: 0.5
  - type: BLOCK_BREAK
    target: ANDESITE
    amount: 0.5
  - type: BLOCK_BREAK
    target: GRANITE
    amount: 0.5
  - type: BLOCK_BREAK
    target: TUFF
    amount: 0.5
  
  # 석탄 계열
  - type: BLOCK_BREAK
    target: COAL_ORE
    amount: 5.0
  - type: BLOCK_BREAK
    target: DEEPSLATE_COAL_ORE
    amount: 6.0

  # 철 계열
  - type: BLOCK_BREAK
    target: IRON_ORE
    amount: 10.0
  - type: BLOCK_BREAK
    target: DEEPSLATE_IRON_ORE
    amount: 12.0
  - type: BLOCK_BREAK
    target: RAW_IRON_BLOCK
    amount: 20.0

  # 구리 계열
  - type: BLOCK_BREAK
    target: COPPER_ORE
    amount: 8.0
  - type: BLOCK_BREAK
    target: DEEPSLATE_COPPER_ORE
    amount: 10.0

  # 금 계열
  - type: BLOCK_BREAK
    target: GOLD_ORE
    amount: 20.0
  - type: BLOCK_BREAK
    target: DEEPSLATE_GOLD_ORE
    amount: 25.0
  - type: BLOCK_BREAK
    target: NETHER_GOLD_ORE
    amount: 15.0

  # 레드스톤 계열
  - type: BLOCK_BREAK
    target: REDSTONE_ORE
    amount: 12.0
  - type: BLOCK_BREAK
    target: DEEPSLATE_REDSTONE_ORE
    amount: 15.0

  # 청금석 계열
  - type: BLOCK_BREAK
    target: LAPIS_ORE
    amount: 15.0
  - type: BLOCK_BREAK
    target: DEEPSLATE_LAPIS_ORE
    amount: 18.0

  # 다이아몬드 계열
  - type: BLOCK_BREAK
    target: DIAMOND_ORE
    amount: 50.0
  - type: BLOCK_BREAK
    target: DEEPSLATE_DIAMOND_ORE
    amount: 60.0

  # 에메랄드 계열
  - type: BLOCK_BREAK
    target: EMERALD_ORE
    amount: 100.0
  - type: BLOCK_BREAK
    target: DEEPSLATE_EMERALD_ORE
    amount: 120.0

  # 네더 광물
  - type: BLOCK_BREAK
    target: NETHER_QUARTZ_ORE
    amount: 15.0
  - type: BLOCK_BREAK
    target: ANCIENT_DEBRIS
    amount: 200.0

# 레벨업 보상
rewards:
  level_10:
    message: "&e[광부] &f단단한 피부(Passive)가 해금되었습니다! (받는 물리 데미지 5% 감소)"
    stats:
      CON: 5
      STR: 2
    skill_unlock: "tough_skin"

  level_30:
    message: "&e[광부] &f슈퍼 히트(Active)를 배웠습니다! (광물 즉시 제련)"
    stats:
      CON: 10
      STR: 5
    skill_unlock: "superheat"

  level_50:
    message: "&e[광부] &f광맥 발견(Passive) 능력을 깨달았습니다!"
    stats:
      CON: 15
      STR: 8
    skill_unlock: "miner_blast"

  level_80:
    message: "&e[광부] &6전설의 광부&f 칭호를 획득했습니다!"
    stats:
      CON: 20
      STR: 10
    money: 100000
    skill_unlock: "gem_detector"

  level_100:
    message: "&e[광부] &c마스터 광부&f 칭호를 획득했습니다!"
    stats:
      CON: 30
      STR: 15
    money: 500000
    commands:
      - "lp user %player% parent add master_miner"

# 레벨별 스탯 상승 (1레벨당)
stats_per_level:
  CON: 1.0
  STR: 0.5

# 스킬 목록
skills:
  tough_skin:
    name: "단단한 피부"
    type: PASSIVE
    unlock_level: 10
    description: "물리 데미지를 5% 감소시킵니다."
  
  superheat:
    name: "슈퍼 히트"
    type: ACTIVE
    unlock_level: 30
    cooldown: 300
    mana_cost: 30
    description: "30초간 채광한 광물을 즉시 제련 상태로 획득합니다."
  
  miner_blast:
    name: "광맥 발견"
    type: ACTIVE
    unlock_level: 50
    cooldown: 30
    mana_cost: 20
    description: "주변 3×3×3 범위의 광석을 한 번에 채굴합니다."
  
  gem_detector:
    name: "보석 탐지"
    type: PASSIVE
    unlock_level: 80
    description: "돌 채광 시 0.1% 확률로 랜덤 보석을 드롭합니다."
